name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: MSYS2 Setup
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          make
          wget
          mingw-w64-x86_64-7zip
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-bullet
          mingw-w64-x86_64-libpng
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-libjpeg-turbo
          mingw-w64-x86_64-libtiff
          mingw-w64-x86_64-libogg
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-libtheora
          mingw-w64-x86_64-opus
          mingw-w64-x86_64-opusfile

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        make init
        make

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: DxLib.dll
        path: "*.dll"

    - name: Upload Import Library
      uses: actions/upload-artifact@v4
      with:
        name: DxLib.lib
        path: DxLib.lib